//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public int ID { get; set; }
        public string TenDangNhap { get; set; }
        public byte[] MatKhau { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayDangKi { get; set; }
        public string MaOTP { get; set; }
        public Nullable<System.DateTime> ThoiGianNhanOTP { get; set; }
        public Nullable<bool> TrangThaiXacThuc { get; set; }
        public string QuyenHan { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> SoSachMuon { get; set; }
        public Nullable<bool> BiKhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
